AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >-
  This AWS Event Fork Pipelines app indexes events from the given Amazon SNS topic into an Amazon Elasticsearch Service domain for search
  and analytics, using an Amazon Kinesis Data Firehose stream.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: fork-event-search-analytics-pipeline
    Description: >-
      This AWS Event Fork Pipelines app indexes events from the given Amazon SNS topic into an Amazon Elasticsearch Service domain for search
      and analytics, using an Amazon Kinesis Data Firehose stream.
    Author: AWS
    SpdxLicenseId: MIT-0
    LicenseUrl: ../../LICENSE
    ReadmeUrl: README.md
    Labels: [sns, aws-event-fork-pipelines, event, search, analytics]
    HomePageUrl: https://github.com/aws-samples/aws-serverless-event-fork-pipelines
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/aws-samples/aws-serverless-event-fork-pipelines/tree/1.0.0/pipelines/event-search-analytics-pipeline

Parameters:
  TopicArn:
    Description: The ARN of the SNS topic to which this instance of the pipeline should be subscribed.
    Type: String
  SearchIndexName:
    Description: The name of the Elasticsearch index used for indexing the events, making them available for search and analytics. Max string length of 80, all lowecase, no special characters.
    Type: String
    MaxLength: 80
  SearchTypeName:
    Description: The name of the Elasticsearch type used for organizing the events in an index. Max string length of 100, all lowercase, not starting with an underscore. 
    Type: String
    MaxLength: 100
  SearchDomainArn:
    Description: "[Optional] The ARN of the Elasticsearch domain to be used. A domain is an Elasticsearch cluster in the AWS cloud, setting the compute and storage configuration needed. If you don’t enter any value, then a new domain with default configuration is created in your account."
    Type: String
    Default: ''
  SubscriptionFilterPolicy:
    Description: "[Optional] The SNS subscription filter policy, in JSON format, used for filtering the incoming events. The filter policy decides which events are processed by this pipeline. If you don’t enter any value, then no filtering is used, meaning all events are processed."
    Type: String
    Default: ''
  SearchIndexRotationPeriod:
    Description: "[Optional] The rotation period of the Elasticsearch index. Index rotation appends a timestamp to the index name, facilitating the expiration of old data. Five options are available, namely NoRotation, OneHour, OneDay, OneWeek, and OneMonth. If you don’t enter any value, then option NoRotation is used."
    Type: String
    AllowedValues:
      - NoRotation
      - OneHour
      - OneDay
      - OneWeek
      - OneMonth
    Default: NoRotation
  StreamRetryDurationInSeconds:
    Description: "[Optional] The retry duration for cases when the stream is unable to index events in the Elasticsearch index. If you don’t enter any value, then the pipeline sets 300 seconds."
    Type: Number
    MinValue: 0
    MaxValue: 7200
    Default: 300
  StreamPrefix:
    Description: "[Optional] The string prefix used for naming files stored in the S3 bucket. If you don’t enter any value, then no prefix is used."
    Type: String
    Default: ''
  StreamCompressionFormat:
    Description: "[Optional] The format used for compressing the incoming events. Three options are available, namely GZIP, ZIP, and SNAPPY. If you don’t enter any value, then data compression is disabled."
    Type: String
    AllowedValues:
      - UNCOMPRESSED
      - GZIP
      - ZIP
      - Snappy
    Default: UNCOMPRESSED
  StreamBufferingIntervalInSeconds:
    Description: "[Optional] The amount of seconds for which the stream should buffer incoming events before delivering them to the destination. Any integer value from 60 to 900 seconds. If you don't enter any value, then 300 is used."
    Type: Number
    MinValue: 60
    MaxValue: 900
    Default: 300
  StreamBufferingSizeInMBs:
    Description: "[Optional] The amount of data, in MB, that the stream should buffer before delivering them to the destination. Any integer value from 1 to 100. If you don't enter any value, then 5 is used."
    Type: Number
    MinValue: 1
    MaxValue: 128
    Default: 5
  DataTransformationFunctionArn:
    Description: "[Optional] The ARN of the Lambda function used for transforming the incoming events. If you don’t enter any value, then data transformation is disabled."
    Type: String
    Default: ''
  LogLevel:
    Type: String
    Description: "[Optional] The level used for logging the execution of the Lambda function that polls events from the SQS queue. Four options are available, namely DEBUG, INFO, WARNING, and ERROR. If you don’t enter any value, then INFO is used."
    Default: INFO

Conditions:
  FilterPolicyEnabled:
    !Not [!Equals [!Ref SubscriptionFilterPolicy, '']]
  DataTransformationEnabled:
    !Not [!Equals [!Ref DataTransformationFunctionArn, '']]
  CreateAnalyticsDomain:
    !Equals [!Ref SearchDomainArn, '']

Resources:
  AnalyticsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt AnalyticsQueue.Arn
      RawMessageDelivery: true
      TopicArn: !Ref TopicArn

  AnalyticsQueue:
    Type: AWS::SQS::Queue

  AnalyticsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref AnalyticsQueue
      PolicyDocument:
        Version: '2012-10-17'
        Id: AnalyticsQueuePolicy
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sns.amazonaws.com
            Action:
              - sqs:SendMessage
            Resource:
              - !GetAtt AnalyticsQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref TopicArn

  AnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: process_records.handler
      Runtime: python3.7
      Tracing: Active
      Timeout: 5
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
          FIREHOSE_DELIVERY_STREAM_NAME: !Ref AnalyticsStream
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - firehose:PutRecord
            Resource:
              - !Sub ${AnalyticsStream.Arn}
      Events:
        Mapping:
          Type: SQS
          Properties:
            Queue: !GetAtt AnalyticsQueue.Arn
            BatchSize: 10

  AnalyticsStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamType: DirectPut
      ElasticsearchDestinationConfiguration:
        DomainARN: !If [CreateAnalyticsDomain, !GetAtt AnalyticsDomain.DomainArn, !Ref SearchDomainArn]
        IndexName: !Ref SearchIndexName
        TypeName: !Ref SearchTypeName
        IndexRotationPeriod: !Ref SearchIndexRotationPeriod
        RetryOptions:
          DurationInSeconds: !Ref StreamRetryDurationInSeconds
        RoleARN: !GetAtt AnalyticsStreamRole.Arn
        BufferingHints:
          IntervalInSeconds: !Ref StreamBufferingIntervalInSeconds
          SizeInMBs: !Ref StreamBufferingSizeInMBs
        S3BackupMode: FailedDocumentsOnly
        S3Configuration:
          BucketARN: !GetAtt AnalyticsDeadLetterBucket.Arn
          RoleARN: !GetAtt AnalyticsStreamRole.Arn
          Prefix: !Ref StreamPrefix
          BufferingHints:
            IntervalInSeconds: 60
            SizeInMBs: 5
          CompressionFormat: !Ref StreamCompressionFormat
        ProcessingConfiguration: !If
          - DataTransformationEnabled
          - Enabled: true
            Processors:
              - Type: Lambda
                Parameters:
                  - ParameterName: LambdaArn
                    ParameterValue: !Ref DataTransformationFunctionArn
          - !Ref AWS::NoValue

  AnalyticsStreamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action:
            - sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub ${AWS::AccountId}
      Policies:
        - PolicyName: fh-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Resource:
                  - !GetAtt AnalyticsDeadLetterBucket.Arn
                  - !Sub ${AnalyticsDeadLetterBucket.Arn}/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/kinesisfirehose/*
              - Effect: "Allow"
                Action:
                  - es:DescribeElasticsearchDomain
                  - es:DescribeElasticsearchDomains
                  - es:DescribeElasticsearchDomainConfig
                  - es:ESHttpGet
                  - es:ESHttpPut
                  - es:ESHttpPost
                Resource:
                  - !If [CreateAnalyticsDomain, !GetAtt AnalyticsDomain.DomainArn, !Ref SearchDomainArn]
                  - !Sub
                      - ${SearchDomainArn}/*
                      - SearchDomainArn: !If [CreateAnalyticsDomain, !GetAtt AnalyticsDomain.DomainArn, !Ref SearchDomainArn]
              - !If
                  - DataTransformationEnabled
                  - Effect: Allow
                    Action:
                      - lambda:InvokeFunction
                    Resource:
                      - !Ref DataTransformationFunctionArn
                  - !Ref AWS::NoValue

  AnalyticsDeadLetterBucket:
    Type: AWS::S3::Bucket

  AnalyticsSubscriptionFilterPolicy:
    Type: AWS::Serverless::Application
    Condition: FilterPolicyEnabled
    Properties:
      Location: ../../util/sns-subscription-filter-policy-string/.aws-sam/build/template.yaml
      Parameters:
        TopicArn: !Ref TopicArn
        SubscriptionArn: !Ref AnalyticsSubscription
        SubscriptionFilterPolicy: !Ref SubscriptionFilterPolicy
        LogLevel: !Ref LogLevel

  AnalyticsDomain:
    Condition: CreateAnalyticsDomain
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchVersion: '6.3'
      ElasticsearchClusterConfig:
        InstanceCount: 2
        ZoneAwarenessEnabled: true
        InstanceType: m5.large.elasticsearch
        DedicatedMasterEnabled: true
        DedicatedMasterType: m5.large.elasticsearch
        DedicatedMasterCount: 3
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 20

Outputs:
  AnalyticsDeadLetterBucketName:
    Description: Dead-letter S3 bucket name
    Value: !Ref AnalyticsDeadLetterBucket
  AnalyticsDeadLetterBucketArn:
    Description: Dead-letter S3 bucket ARN
    Value: !GetAtt AnalyticsDeadLetterBucket.Arn
  AnalyticsDomainName:
    Description: Analytics ES domain name
    Value: !Ref AnalyticsDomain
    Condition: CreateAnalyticsDomain
  AnalyticsDomainArn:
    Description: Analytics ES domain ARN
    Value: !GetAtt AnalyticsDomain.DomainArn
    Condition: CreateAnalyticsDomain
  AnalyticsDomainEndpoint:
    Description: Analytics ES domain endpoint
    Value: !GetAtt AnalyticsDomain.DomainEndpoint
    Condition: CreateAnalyticsDomain
